name: Daily City Script and Deploy to GitHub Pages

on:
  schedule:
    - cron: '0 1 * * *'  # Schedule to run every day at 1 am
  workflow_dispatch:

jobs:
  run-script-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Change this to your Python version if needed

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt  # If you have any dependencies

      - name: Configure Git
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git remote add origin_with_token "https://${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}"
          git fetch origin_with_token gh-pages

      - name: Run City Script
        run: python city.py locations.txt

      - name: Move JSON File to Docs Directory
        run: |
          mkdir -p docs
          mv world_weather.json docs/world_weather.json

      - name: Commit and Push to GitHub Pages
        run: |
          git checkout -b gh-pages
          git add docs/world_weather.json
          git commit -m "Deploy world_weather.json to GitHub Pages"
          git pull origin_with_token main
          git push --force origin_with_token gh-pages

      - name: Clean Up
        run: |
          git checkout main  # Change 'main' to your branch name
          git branch -D gh-pages
