name: Daily City Script and Deploy to GitHub Pages

on:
  schedule:
    - cron: '0 1 * * *'  # Schedule to run every day at 1 am
  workflow_dispatch:

jobs:
  run-script-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Change this to your Python version if needed

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt  # If you have any dependencies

      - name: Run City Script
        run: python city.py locations.txt

      - name: Move JSON File to data Directory
        run: |
          mkdir -p data
          mv world_weather.json data/world_weather.json

      - name: Configure Git
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"

      - name: Commit and Push to Main
        run: |
          git add data/world_weather.json
          git commit -m "Deploy world_weather.json to GitHub Pages"
          git pull origin main
          git push origin main
